name: smart_horizon_home
description: "A smart home management application with Firebase integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Plugins
  image_picker: ^1.2.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_svg: ^2.0.7
  qr_code_scanner:
    git:
      url: https://github.com/juliuscanute/qr_code_scanner.git
      ref: master

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.0.2
  firebase_database: ^11.3.10

  # State management
  provider: ^6.1.2

  # Local notifications
  flutter_local_notifications: ^17.2.1

  # Local storage
  shared_preferences: ^2.3.2

  # API calls
  http: ^1.2.2
  flutter_advanced_drawer: ^1.5.0
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/icons/
    - lib/icons/weather/
